export enum ActionTypeStates {
  INPROGRESS = '_INPROGRFESS',
  SUCCESS = '_SUCCESS',
  FAILED = '_FAILED',
}

enum ActionTypeKeys {
  SINGIN_INPROGRESS = '@auth/SINGNIN_INPROGRESS',
  SINGIN_SUCCESS = '@auth/SINGNIN_SUCCESS',
  SINGIN_FAILED = '@auth/SINGNIN_FAILED',
  SINGOUT_INPROGRESS = '@auth/SINGNOUT_INPROGRESS',
  SINGOUT_SUCCESS = '@auth/SINGNOUT_SUCCESS',
  SINGOUT_FAILED = '@auth/SINGNOUT_FAILED',
  CALLBACK_SUCCESS = '@auth/CALLBACK_SUCCESS',
  ACQUIRE_ACCESSTOKEN_INPROGRESS = '@auth/ACQUIRE_ACCESSTOKEN_INPROGRESS',
  ACQUIRE_IDTOKEN_SUCCESS = '@auth/ACQUIRE_IDTOKEN_SUCCESS',
}

export default ActionTypeKeys;
